name: API and Web UI Automation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  run-automation-test:
    runs-on: ubuntu-latest

    steps:
    # setup java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    # install chrome browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v0.0.0
      
    # setup graldew
    - name: Setup gradlew
      run: chmod +x gradlew 
      
    # Execute gradle command for running cucumber test
    - name: Execute Test
      run: ./gradlew test
    # Archive Test Result
    - name: Archive Test Result
      uses: actions/upload-artifact@v3.1.0
      if: always()
      with:
        name: Cucumber Report
        path: reports
    
